version: '3.9'

services:
  postgres:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=sharma0402
      - POSTGRES_USER=root
      - POSTGRES_DB=e-commerce